# ============================================
# GridSpace — Cloud Build Pipeline
# Triggers on push to main → builds → deploys to Cloud Run
# ============================================

steps:
  # Step 1: Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/sarath-personal-471604/gridspace/gridspace:$COMMIT_SHA"
      - "-t"
      - "us-central1-docker.pkg.dev/sarath-personal-471604/gridspace/gridspace:latest"
      - "."
    timeout: "600s"

  # Step 2: Push to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "--all-tags"
      - "us-central1-docker.pkg.dev/sarath-personal-471604/gridspace/gridspace"

  # Step 3: Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "gridspace"
      - "--image=us-central1-docker.pkg.dev/sarath-personal-471604/gridspace/gridspace:$COMMIT_SHA"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--port=8080"
      - "--cpu=1"
      - "--memory=512Mi"
      - "--min-instances=0"
      - "--max-instances=5"
      - "--concurrency=200"
      - "--timeout=3600"
      - "--session-affinity"
      - "--vpc-connector=gridspace-connector"
      - "--vpc-egress=private-ranges-only"
      # Environment variables
      - "--set-env-vars=NODE_ENV=production"
      - "--set-env-vars=PORT=8080"
      # Secrets from Secret Manager
      - "--set-secrets=DATABASE_URL=database-url:latest"
      - "--set-secrets=REDIS_URL=redis-url:latest"
      - "--set-secrets=JWT_SECRET=jwt-secret:latest"
      - "--set-secrets=JWT_REFRESH_SECRET=jwt-refresh-secret:latest"
      # These will be added later when OAuth is configured:
      # - '--set-secrets=GOOGLE_CLIENT_ID=google-client-id:latest'
      # - '--set-secrets=GOOGLE_CLIENT_SECRET=google-client-secret:latest'
      # - '--set-secrets=GITHUB_CLIENT_ID=github-client-id:latest'
      # - '--set-secrets=GITHUB_CLIENT_SECRET=github-client-secret:latest'
      # Dynamic env vars set from Cloud Run URL
      - "--set-env-vars=JWT_EXPIRES_IN=15m"
      - "--set-env-vars=JWT_REFRESH_EXPIRES_IN=7d"
      - "--set-env-vars=EMAIL_FROM=noreply@gridspace.app"

  # Step 4: Set CLIENT_URL to the deployed Cloud Run URL
  # (Cloud Run URL is known after first deploy — update this)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        SERVICE_URL=$(gcloud run services describe gridspace --region=us-central1 --format="value(status.url)")
        gcloud run services update gridspace \
          --region=us-central1 \
          --set-env-vars="CLIENT_URL=$${SERVICE_URL}" \
          --set-env-vars="SERVER_URL=$${SERVICE_URL}"

# Store images in Artifact Registry
images:
  - "us-central1-docker.pkg.dev/sarath-personal-471604/gridspace/gridspace:$COMMIT_SHA"
  - "us-central1-docker.pkg.dev/sarath-personal-471604/gridspace/gridspace:latest"

# Build timeout: 15 minutes
timeout: "900s"

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
